### ISSUE TITLE
www.ncsc.gov.uk

### ISSUE THREAD

**Issue by Joshua-Noakes1** [Xenios91/AlienVaultURLS#1]
[www.ncsc.gov.uk](https://www.ncsc.gov.uk/) is the official domain for the UK governments National Cyber Security Centre, I would be surprised if the government is spreading malware from that domain at least.
![image](https://user-images.githubusercontent.com/53623449/165334354-ead7cbb8-b546-4aa9-b6e5-254198224b98.png)

**Comment by Xenios91** [comment]
Good find, ill remove it.

**Comment by Xenios91** [comment]
@Joshua-Noakes1, im adding a whitelist page, if you see anything else like that and want to, submit a pull request with the url added and ill update the script later to ensure it isnt added to the blacklist.

**Comment by Joshua-Noakes1** [comment]
Will do thanks for the support

**Comment by Xenios91** [comment]
@Joshua-Noakes1 to help, i updated it really quick to run each url through talos to check if its trusted. This way we can help remove false positives, especially when its so obvious such as the example you provided.
