### ISSUE TITLE
Curious Question

### ISSUE THREAD

**Issue by rexdivakar** [Xenios91/AlienVaultURLS#2]
Hey Buddy just curious, Can you please explain me how are you grabbing these urls and how do you validate those urls ??

**Comment by Xenios91** [comment]
> 
I'm pulling them from the AlienVault OTX API, then running each by Talos to get the reputation of them, if the reputation is not positive its added to the list. There absolutely is the chance there will be false positives in there, if so add them to the whitelist and make a pull request so they are removed. 

Is this the best technique for this? Probably not, its just me trying to tinker a little when I can and hopefully make something good for the community.

**Comment by Xenios91** [comment]
I plan on making the code available in the future once its ironed out more.
