### ISSUE TITLE
JavaScript in URL list?

### ISSUE THREAD

**Issue by JACGWD** [Xenios91/AlienVaultURLS#3]
I just updated the list and I see this in the log:

Analyzed 6824 domains, 2 domains invalid!

Sample of invalid domains:
- t,i,s=this.options\;this.element.show
 - t,i,s=this.options;this.element.show

[i] List has been updated

**Comment by Xenios91** [comment]
Thanks for helping with that, I also fixed the script to exclude urls like this.
